### GET all
GET http://localhost:3003/api/blogs

### POST new blog 
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Test blog",
    "author": "Jacob Gayban",
    "url": "http://localhost/bloglist",
    "likes": "999"
}

