### GET all users
GET http://localhost:3003/api/users

### POST new user
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "quincinia",
    "name": "jacob gayban",
    "password": "secret"
}

### Second test user
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "quintwinia",
    "name": "jacob gayban?",
    "password": "secret"
}

### Non-unique username
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "quincinia",
    "name": "jacob gayban?",
    "password": "secret"
}

### Invalid username
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "qu",
    "name": "jacob gayban",
    "password": "secret"
}


### Invalid password
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "quintwinia",
    "name": "jacob gayban",
    "password": "se"
}